### ISSUE TITLE
Informação errada no topo do ficheiro sendout-api.js

### ISSUE THREAD

**Issue by JoseCage** [flowck/sendout-api#1]
@flowck Suponho que tenhas confundido o proxypay com o sendout, pois no topo do ficheiro principal do módulo devia constar a descrição do sendout porém colocaste a do proxypay.

Abaixo o erro: 

Linha 2:   [ProxyPay API Wrapper](https://github.com/flowck/sendout-api/blob/master/lib/sendout-api.js#L2)
Linha 3:  [https://flowck.github.io/proxypay-api](https://github.com/flowck/sendout-api/blob/master/lib/sendout-api.js#L3)

**Comment by flowck** [comment]
Obrigado @JoseCage. Corrigido no commit [a6fa0aa](https://github.com/flowck/sendout-api/commit/a6fa0aa7429f0ed718a5cadb6bcf672de1d3f83d)

**Comment by JoseCage** [comment]
Great... 👍
